config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'static_pages/home'
  root to: 'static_pages#home'
  resources :event_proofs
  resources :event_comments
  resources :event_registrations
  resources :events
  devise_for :users, :controllers => {:registrations => "registrations"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event_proof.rb
class EventProof < ApplicationRecord
    belongs_to :user
    belongs_to :event
    
    has_one_attached :image
end

app/controllers/event_proofs_controller.rb
class EventProofsController < ApplicationController
  before_action :set_event_proof, only: [:show, :edit, :update, :destroy]

  # GET /event_proofs
  # GET /event_proofs.json
  def index
    @event_proofs = EventProof.all
  end

  # GET /event_proofs/1
  # GET /event_proofs/1.json
  def show
  end

  # GET /event_proofs/new
  def new
    @event_proof = EventProof.new
  end

  # GET /event_proofs/1/edit
  def edit
  end

  # POST /event_proofs
  # POST /event_proofs.json
  def create
    @event_proof = EventProof.new(event_proof_params)

    respond_to do |format|
      if @event_proof.save
        format.html { redirect_to @event_proof, notice: 'イベントの証拠は正常に作成された。' }
        format.json { render :show, status: :created, location: @event_proof }
      else
        format.html { render :new }
        format.json { render json: @event_proof.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_proofs/1
  # PATCH/PUT /event_proofs/1.json
  def update
    respond_to do |format|
      if @event_proof.update(event_proof_params)
        format.html { redirect_to @event_proof, notice: 'イベントの証拠が正常に更新された。' }
        format.json { render :show, status: :ok, location: @event_proof }
      else
        format.html { render :edit }
        format.json { render json: @event_proof.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_proofs/1
  # DELETE /event_proofs/1.json
  def destroy
    @event_proof.destroy
    respond_to do |format|
      format.html { redirect_to event_proofs_url, notice: 'イベントの証拠は正常に削除された。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_proof
      @event_proof = EventProof.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_proof_params
      params.require(:event_proof).permit(:user_id, :event_id, :note, :image)
    end
end

app/helpers/event_proofs_helper.rb
module EventProofsHelper
end

app/views/event_proofs/_form.html.erb
<%= form_with(model: event_proof, local: true) do |form| %>
  <% if event_proof.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event_proof.errors.count, "error") %> prohibited this event_proof from being saved:</h2>

      <ul>
        <% event_proof.errors.full_messages.each do |message| %>
          <li><%= メッセージ %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<%
=begin %>
  <div class="field">
    <%= form.label :user_id, "ユーザーのID" %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :event_id, "イベントのID" %>
    <%= form.number_field :event_id %>
  </div>

  <div class="field">
    <%= form.label :image, "画像" %>
    <%= form.file_field :image %><br>
  </div>
  <%
=end %>
  <p>
    <strong>ユーザー:</strong>
    <%= @event_proof.user.email if @event_proof.user %>
  </p>
  
  <p>
    <strong>イベント:</strong>
    <%= @event_proof.event.name if @event_proof.event %>
  </p>
  
  <p>
    <% if @event_proof.image.attached? %>
      <strong>画像:</strong><br>
      <%= image_tag @event_proof.image %>
    <% end %>
  </p>

  <div class="field">
    <%= form.label :note, "注意" %>
    <%= form.text_area :note %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/event_proofs/edit.html.erb
<h1>イベントの証拠を更新する</h1>

<%= render 'form', event_proof: @event_proof %>

<%= link_to '表示する', @event_proof %> |
<%= link_to '戻る', event_proofs_path %>

app/views/event_proofs/index.html.erb
<p id="お知らせ"><%= notice%></p>

<h1>イベントの証拠</h1>
<table>
  <thead>
    <tr>
      <%
=begin %>
        <th>ユーザー</th>
        <th>注意</th>
      <%
=end %>
      <th>イベント</th>
      <th>開始時間</th>
      <th>終了時間</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event_proofs.each do |event_proof| %>
    <% if event_proof.user_id == current_user.id %>
      <tr>
        <%
=begin %>
          <td><%= event_proof.user.email if event_proof.user  %></td>
          <td><%= event_proof.note %></td>
        <%
=end %>
        
        <td><%= event_proof.event.name if event_proof.event  %></td>
        <td><%= event_proof.event.startDate %></td>
        <td><%= event_proof.event.endDate %></td>
        <td><%= link_to '表示する', event_proof %></td>
        <td><%= link_to '更新する', edit_event_proof_path(event_proof) %></td>
        <td><%= link_to '削除する', event_proof, method: :delete, data: { confirm: '本気？' } %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
<br>
<%
=begin %>
<%=  link_to 'イベントの証拠を作成する', new_event_proof_path %>
<%
=end %>

app/views/event_proofs/new.html.erb
<h1>イベントの証拠を作成する</h1>

<%= render 'form', event_proof: @event_proof %>

<%= link_to '戻る', event_proofs_path %>

app/views/event_proofs/show.html.erb
<p id="お知らせ"><%= notice%></p>

<p>
  <strong>ユーザー:</strong>
  <%= @event_proof.user.email if @event_proof.user %>
</p>

<p>
  <strong>イベント:</strong>
  <%= @event_proof.event.name if @event_proof.event %>
</p>

<p>
  <% if @event_proof.image.attached? %>
    <strong>画像:</strong><br>
    <%= image_tag @event_proof.image %>
  <% end %>
</p>

<p>
  <strong>注意:</strong>
  <%= @event_proof.note %>
</p>

<%= link_to '更新する', edit_event_proof_path(@event_proof) %> |
<%= link_to '戻る', event_proofs_path %>