config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'static_pages/home'
  root to: 'static_pages#home'
  resources :event_proofs
  resources :event_comments
  resources :event_registrations
  resources :events
  devise_for :users, :controllers => {:registrations => "registrations"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event_registration.rb
class EventRegistration < ApplicationRecord
    belongs_to :user
    belongs_to :event
end

app/controllers/event_registrations_controller.rb
class EventRegistrationsController < ApplicationController
  before_action :set_event_registration, only: [:show, :edit, :update, :destroy]

  # GET /event_registrations
  # GET /event_registrations.json
  def index
    @event_registrations = EventRegistration.all
  end

  # GET /event_registrations/1
  # GET /event_registrations/1.json
  def show
    @event_proof = EventProof.new
  end

  # GET /event_registrations/new
  def new
    @event_registration = EventRegistration.new
  end

  # GET /event_registrations/1/edit
  def edit
  end

  # POST /event_registrations
  # POST /event_registrations.json
  def create
    @event_registration = EventRegistration.new(event_registration_params)

    respond_to do |format|
      if @event_registration.save
        format.html { redirect_to @event_registration, notice: 'Event registration was successfully created.' }
        format.json { render :show, status: :created, location: @event_registration }
      else
        format.html { render :new }
        format.json { render json: @event_registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_registrations/1
  # PATCH/PUT /event_registrations/1.json
  def update
    respond_to do |format|
      if @event_registration.update(event_registration_params)
        format.html { redirect_to @event_registration, notice: 'Event registration was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_registration }
      else
        format.html { render :edit }
        format.json { render json: @event_registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_registrations/1
  # DELETE /event_registrations/1.json
  def destroy
    @event_registration.destroy
    respond_to do |format|
      format.html { redirect_to event_registrations_url, notice: 'Event registration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_registration
      @event_registration = EventRegistration.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_registration_params
      params.require(:event_registration).permit(:user_id, :event_id, :reason)
    end
end

app/helpers/event_registrations_helper.rb
module EventRegistrationsHelper
end

app/views/event_registrations/_form.html.erb
<%= form_with(model: event_registration, local: true) do |form| %>
  <% if event_registration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event_registration.errors.count, "error") %> prohibited this event_registration from being saved:</h2>

      <ul>
        <% event_registration.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :user_id %>
  </div>

  <div class="field">
    <%= form.hidden_field :event_id %>
  </div>

  <div class="field">
    <%= form.label :reason %>
    <%= form.text_area :reason %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/event_registrations/edit.html.erb
<h1>Editing Event Registration</h1>

<%= render 'form', event_registration: @event_registration %>

<%= link_to 'Show', @event_registration %> |
<%= link_to 'Back', event_registrations_path %>

app/views/event_registrations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Event Registrations</h1>

<table>
  <thead>
    <tr>

      <th>Event_name</th>
      <th>Reason</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event_registrations.each do |event_registration| %>
    <% if event_registration.user_id ==  2%>
      <tr>
        <td><%= event_registration.event_id %></td>
        <td><%= event_registration.reason %></td>
        <td><%= link_to 'Show', event_registration %></td>
        <td><%= link_to 'Edit', edit_event_registration_path(event_registration) %></td>
        <td><%= link_to 'Destroy', event_registration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event Registration', new_event_registration_path %>
<%= link_to "ログアウト", destroy_user_session_path, method: :delete %>

app/views/event_registrations/new.html.erb
<h1>New Event Registration</h1>

<%= render 'form', event_registration: @event_registration %>

<%= link_to 'Back', event_registrations_path %>

app/views/event_registrations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @event_registration.user.email %>
</p>

<p>
  <strong>Event:</strong>
  <%= @event_registration.event.name %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @event_registration.reason %>
</p>

<h2>証拠の追加</h2>
<%= form_with(model: @event_proof, local: true) do |form| %>
  <div class= "field">
    <%= form.label :image, "画像" %>
    <%= form.file_field :image %>
    <%= form.label :note, "注意" %>
    <%= form.text_area :note %>
    <%= form.hidden_field :event_id, :value => @event_registration.event_id %>
    <%= form.hidden_field :user_id, :value => @event_registration.user_id %>
  </div>
  <div class="actions">
    <%= form.submit "証拠を作成する" %>
  </div>
<% end %>

<%= link_to 'Edit', edit_event_registration_path(@event_registration) %> |
<%= link_to 'Back', event_registrations_path %>