config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'static_pages/home'
  root to: 'static_pages#home'
  resources :event_proofs
  resources :event_comments
  resources :event_registrations
  resources :events
  devise_for :users, :controllers => {:registrations => "registrations"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event_comment.rb
class EventComment < ApplicationRecord
    belongs_to :user
    belongs_to :event
end

app/controllers/event_comments_controller.rb
class EventCommentsController < ApplicationController
  before_action :set_event_comment, only: [:show, :edit, :update, :destroy]

  # GET /event_comments
  # GET /event_comments.json
  def index
    @event_comments = EventComment.all
  end

  # GET /event_comments/1
  # GET /event_comments/1.json
  def show
  end

  # GET /event_comments/new
  def new
    @event_comment = EventComment.new
  end

  # GET /event_comments/1/edit
  def edit
  end

  # POST /event_comments
  # POST /event_comments.json
  def create
    @event_comment = EventComment.new(event_comment_params)
    @event_comment.user_id = 1
    
    respond_to do |format|
      if @event_comment.save
        url = "/events/" + @event_comment.event_id.to_s
        format.html { redirect_to url, notice: 'Event comment was successfully created.' }
        format.json { render :show, status: :created, location: @event_comment }
      else
        format.html { render :new }
        format.json { render json: @event_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_comments/1
  # PATCH/PUT /event_comments/1.json
  def update
    respond_to do |format|
      if @event_comment.update(event_comment_params)
        format.html { redirect_to @event_comment, notice: 'Event comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_comment }
      else
        format.html { render :edit }
        format.json { render json: @event_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_comments/1
  # DELETE /event_comments/1.json
  def destroy
    @event_comment.destroy
    respond_to do |format|
      format.html { redirect_to event_comments_url, notice: 'Event comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_comment
      @event_comment = EventComment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_comment_params
      params.require(:event_comment).permit(:user_id, :event_id, :content)
    end
end

app/helpers/event_comments_helper.rb
module EventCommentsHelper
end

app/views/event_comments/_form.html.erb
<%= form_with(model: event_comment, local: true) do |form| %>
  <% if event_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event_comment.errors.count, "error") %> prohibited this event_comment from being saved:</h2>

      <ul>
        <% event_comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.number_field :event_id %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/event_comments/edit.html.erb
<h1>Editing Event Comment</h1>

<%= render 'form', event_comment: @event_comment %>

<%= link_to 'Show', @event_comment %> |
<%= link_to 'Back', event_comments_path %>

app/views/event_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Event Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Event</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event_comments.each do |event_comment| %>
      <tr>
        <td><%= event_comment.user_id %></td>
        <td><%= event_comment.event_id %></td>
        <td><%= event_comment.content %></td>
        <td><%= link_to 'Show', event_comment %></td>
        <td><%= link_to 'Edit', edit_event_comment_path(event_comment) %></td>
        <td><%= link_to 'Destroy', event_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event Comment', new_event_comment_path %>

app/views/event_comments/new.html.erb
<h1>New Event Comment</h1>

<%= render 'form', event_comment: @event_comment %>

<%= link_to 'Back', event_comments_path %>

app/views/event_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @event_comment.user_id %>
</p>

<p>
  <strong>Event:</strong>
  <%= @event_comment.event_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @event_comment.content %>
</p>

<%= link_to 'Edit', edit_event_comment_path(@event_comment) %> |
<%= link_to 'Back', event_comments_path %>